### ISSUE TITLE
No Kali rootfs found. Aborting Error During KernelSU Installation

### ISSUE THREAD

**Issue by nikxso** [poxiao676/Nethunter_KSU_Module#2]
I’ve been trying to install Kali nethunter via KernelSU, but I keep running into the error "No Kali rootfs found. Aborting." I’ve double-checked that the rootfs is in the right place, but the installation doesn’t seem to detect it. all apps installed without any issue but inside Kali app it's just loading,
![1000014330](https://github.com/user-attachments/assets/d0c12242-3184-4779-856e-d18a77b9a41b)
<details>
<summary>Here is logs </summary>

  _  __                    _ ____  _   _ 
 | |/ /___ _ __ _ __   ___| / ___|| | | |
 | ' // _ \ '__| '_ \ / _ \ \___ \| | | |
 | . \  __/ |  | | | |  __/ |___) | |_| |
 |_|\_\___|_|  |_| |_|\___|_|____/ \___/ 

- Preparing image
- Module size: 2.66 GB
- Mounting image
- Current boot slot: _a
- Device is system-as-root
Archive:  /data/user/0/me.weishu.kernelsu/cache/module.zip
  inflating: module.prop
Archive:  /data/user/0/me.weishu.kernelsu/cache/module.zip
  inflating: post-fs-data.sh
  inflating: service.sh
  inflating: system.prop
  inflating: install.sh
  inflating: module.prop
Archive:  /data/user/0/me.weishu.kernelsu/cache/module.zip
  inflating: module.prop
##################################################
####  ############# NetHunter ####################
Unpacking the installer...
Checking for previous version of NetHunter apps and files
Installing apps...
- Installing NetHunter.apk
- Installing NetHunterTerminal.apk
- Installing NetHunter-KeX.apk
- Installing NetHunter-Store.apk
- Installing privileged extension as system app
Done installing apps
Setting up busybox to automatically mount at startup
- Extracting firware files
Archive:  /data/user/0/me.weishu.kernelsu/cache/module.zip
   creating: system/
   creating: system/etc/
   creating: system/etc/firmware/
  inflating: system/etc/firmware/ar7010.fw
  inflating: system/etc/firmware/ar7010_1_1.fw
  inflating: system/etc/firmware/ar9170-1.fw
  inflating: system/etc/firmware/ar9170-2.fw
  inflating: system/etc/firmware/ar9271.fw
   creating: system/etc/firmware/ath10k/
   creating: system/etc/firmware/ath10k/QCA4019/
   creating: system/etc/firmware/ath10k/QCA4019/hw1.0/
  inflating: system/etc/firmware/ath10k/QCA4019/hw1.0/board-2.bin
  inflating: system/etc/firmware/ath10k/QCA4019/hw1.0/firmware-5.bin
   creating: system/etc/firmware/ath10k/QCA6174/
   creating: system/etc/firmware/ath10k/QCA6174/hw2.1/
  inflating: system/etc/firmware/ath10k/QCA6174/hw2.1/board-2.bin
  inflating: system/etc/firmware/ath10k/QCA6174/hw2.1/board.bin
  inflating: system/etc/firmware/ath10k/QCA6174/hw2.1/firmware-5.bin
   creating: system/etc/firmware/ath10k/QCA6174/hw3.0/
  inflating: system/etc/firmware/ath10k/QCA6174/hw3.0/board-2.bin
  inflating: system/etc/firmware/ath10k/QCA6174/hw3.0/board.bin
  inflating: system/etc/firmware/ath10k/QCA6174/hw3.0/firmware-4.bin
  inflating: system/etc/firmware/ath10k/QCA6174/hw3.0/firmware-6.bin
  inflating: system/etc/firmware/ath10k/QCA6174/hw3.0/firmware-sdio-6.bin
   creating: system/etc/firmware/ath10k/QCA9377/
   creating: system/etc/firmware/ath10k/QCA9377/hw1.0/
  inflating: system/etc/firmware/ath10k/QCA9377/hw1.0/board-2.bin
  inflating: system/etc/firmware/ath10k/QCA9377/hw1.0/board.bin
  inflating: system/etc/firmware/ath10k/QCA9377/hw1.0/firmware-5.bin
  inflating: system/etc/firmware/ath10k/QCA9377/hw1.0/firmware-6.bin
  inflating: system/etc/firmware/ath10k/QCA9377/hw1.0/firmware-sdio-5.bin
   creating: system/etc/firmware/ath10k/QCA9887/
   creating: system/etc/firmware/ath10k/QCA9887/hw1.0/
  inflating: system/etc/firmware/ath10k/QCA9887/hw1.0/board.bin
  inflating: system/etc/firmware/ath10k/QCA9887/hw1.0/firmware-5.bin
   creating: system/etc/firmware/ath10k/QCA9888/
   creating: system/etc/firmware/ath10k/QCA9888/hw2.0/
  inflating: system/etc/firmware/ath10k/QCA9888/hw2.0/board-2.bin
  inflating: system/etc/firmware/ath10k/QCA9888/hw2.0/firmware-5.bin
   creating: system/etc/firmware/ath10k/QCA988X/
   creating: system/etc/firmware/ath10k/QCA988X/hw2.0/
  inflating: system/etc/firmware/ath10k/QCA988X/hw2.0/board.bin
  inflating: system/etc/firmware/ath10k/QCA988X/hw2.0/firmware-4.bin
  inflating: system/etc/firmware/ath10k/QCA988X/hw2.0/firmware-5.bin
   creating: system/etc/firmware/ath10k/QCA9984/
   creating: system/etc/firmware/ath10k/QCA9984/hw1.0/
  inflating: system/etc/firmware/ath10k/QCA9984/hw1.0/board-2.bin
  inflating: system/etc/firmware/ath10k/QCA9984/hw1.0/firmware-5.bin
   creating: system/etc/firmware/ath10k/QCA99X0/
   creating: system/etc/firmware/ath10k/QCA99X0/hw2.0/
  inflating: system/etc/firmware/ath10k/QCA99X0/hw2.0/board-2.bin
  inflating: system/etc/firmware/ath10k/QCA99X0/hw2.0/firmware-5.bin
   creating: system/etc/firmware/ath10k/WCN3990/
   creating: system/etc/firmware/ath10k/WCN3990/hw1.0/
  inflating: system/etc/firmware/ath10k/WCN3990/hw1.0/board-2.bin
  inflating: system/etc/firmware/ath10k/WCN3990/hw1.0/firmware-5.bin
   creating: system/etc/firmware/ath9k_htc/
  inflating: system/etc/firmware/ath9k_htc/htc_7010-1.4.0.fw
  inflating: system/etc/firmware/ath9k_htc/htc_9271-1.4.0.fw
  inflating: system/etc/firmware/bluetooth_rxtx.bin
   creating: system/etc/firmware/brcm/
  inflating: system/etc/firmware/brcm/bcm43xx-0.fw
  inflating: system/etc/firmware/brcm/bcm43xx_hdr-0.fw
  inflating: system/etc/firmware/brcm/brcmfmac4335-sdio.bin
  inflating: system/etc/firmware/brcm/brcmfmac4339-sdio.bin
  inflating: system/etc/firmware/brcm/brcmfmac4354-sdio.bin
  inflating: system/etc/firmware/carl9170-1.fw
  inflating: system/etc/firmware/hackrf_jawbreaker_usb.bin
  inflating: system/etc/firmware/hackrf_one_usb.bin
  inflating: system/etc/firmware/htc_7010.fw
  inflating: system/etc/firmware/htc_9271.fw
  inflating: system/etc/firmware/mt7601u.bin
  inflating: system/etc/firmware/rt2561.bin
  inflating: system/etc/firmware/rt2561s.bin
  inflating: system/etc/firmware/rt2661.bin
  inflating: system/etc/firmware/rt2860.bin
  inflating: system/etc/firmware/rt2870.bin
  inflating: system/etc/firmware/rt3070.bin
  inflating: system/etc/firmware/rt3071.bin
  inflating: system/etc/firmware/rt3290.bin
  inflating: system/etc/firmware/rt73.bin
   creating: system/etc/firmware/rtl_bt/
  inflating: system/etc/firmware/rtl_bt/rtl8192ee_fw.bin
  inflating: system/etc/firmware/rtl_bt/rtl8192eu_fw.bin
  inflating: system/etc/firmware/rtl_bt/rtl8723a_fw.bin
  inflating: system/etc/firmware/rtl_bt/rtl8723b_fw.bin
  inflating: system/etc/firmware/rtl_bt/rtl8723bs_config-OBDA8723.bin
  inflating: system/etc/firmware/rtl_bt/rtl8723bs_fw.bin
  inflating: system/etc/firmware/rtl_bt/rtl8723d_config.bin
  inflating: system/etc/firmware/rtl_bt/rtl8723d_fw.bin
  inflating: system/etc/firmware/rtl_bt/rtl8761a_fw.bin
  inflating: system/etc/firmware/rtl_bt/rtl8761b_config.bin
  inflating: system/etc/firmware/rtl_bt/rtl8761b_fw.bin
  inflating: system/etc/firmware/rtl_bt/rtl8761bu_config.bin
  inflating: system/etc/firmware/rtl_bt/rtl8761bu_fw.bin
  inflating: system/etc/firmware/rtl_bt/rtl8812ae_fw.bin
  inflating: system/etc/firmware/rtl_bt/rtl8821a_fw.bin
  inflating: system/etc/firmware/rtl_bt/rtl8821c_config.bin
  inflating: system/etc/firmware/rtl_bt/rtl8821c_fw.bin
  inflating: system/etc/firmware/rtl_bt/rtl8821cs_config.bin
  inflating: system/etc/firmware/rtl_bt/rtl8821cs_fw.bin
  inflating: system/etc/firmware/rtl_bt/rtl8822b_config.bin
  inflating: system/etc/firmware/rtl_bt/rtl8822b_fw.bin
  inflating: system/etc/firmware/rtl_bt/rtl8822cs_config.bin
  inflating: system/etc/firmware/rtl_bt/rtl8822cs_fw.bin
  inflating: system/etc/firmware/rtl_bt/rtl8822cu_config.bin
  inflating: system/etc/firmware/rtl_bt/rtl8822cu_fw.bin
  inflating: system/etc/firmware/rtl_bt/rtl8851bu_config.bin
  inflating: system/etc/firmware/rtl_bt/rtl8851bu_fw.bin
  inflating: system/etc/firmware/rtl_bt/rtl8852au_config.bin
  inflating: system/etc/firmware/rtl_bt/rtl8852au_fw.bin
  inflating: system/etc/firmware/rtl_bt/rtl8852bu_config.bin
  inflating: system/etc/firmware/rtl_bt/rtl8852bu_fw.bin
  inflating: system/etc/firmware/rtl_bt/rtl8852cu_config.bin
  inflating: system/etc/firmware/rtl_bt/rtl8852cu_fw.bin
  inflating: system/etc/firmware/rtl_bt/rtl8852cu_fw_v2.bin
   creating: system/etc/firmware/rtl_nic/
  inflating: system/etc/firmware/rtl_nic/rtl8105e-1.fw
  inflating: system/etc/firmware/rtl_nic/rtl8106e-1.fw
  inflating: system/etc/firmware/rtl_nic/rtl8106e-2.fw
  inflating: system/etc/firmware/rtl_nic/rtl8107e-2.fw
  inflating: system/etc/firmware/rtl_nic/rtl8125a-3.fw
  inflating: system/etc/firmware/rtl_nic/rtl8125b-1.fw
  inflating: system/etc/firmware/rtl_nic/rtl8125b-2.fw
  inflating: system/etc/firmware/rtl_nic/rtl8153a-2.fw
  inflating: system/etc/firmware/rtl_nic/rtl8153a-3.fw
  inflating: system/etc/firmware/rtl_nic/rtl8153a-4.fw
  inflating: system/etc/firmware/rtl_nic/rtl8153b-2.fw
  inflating: system/etc/firmware/rtl_nic/rtl8153c-1.fw
  inflating: system/etc/firmware/rtl_nic/rtl8156a-2.fw
  inflating: system/etc/firmware/rtl_nic/rtl8156b-2.fw
  inflating: system/etc/firmware/rtl_nic/rtl8168d-1.fw
  inflating: system/etc/firmware/rtl_nic/rtl8168d-2.fw
  inflating: system/etc/firmware/rtl_nic/rtl8168e-1.fw
  inflating: system/etc/firmware/rtl_nic/rtl8168e-2.fw
  inflating: system/etc/firmware/rtl_nic/rtl8168e-3.fw
  inflating: system/etc/firmware/rtl_nic/rtl8168f-1.fw
  inflating: system/etc/firmware/rtl_nic/rtl8168f-2.fw
  inflating: system/etc/firmware/rtl_nic/rtl8168fp-3.fw
  inflating: system/etc/firmware/rtl_nic/rtl8168g-1.fw
  inflating: system/etc/firmware/rtl_nic/rtl8168g-2.fw
  inflating: system/etc/firmware/rtl_nic/rtl8168g-3.fw
  inflating: system/etc/firmware/rtl_nic/rtl8168h-1.fw
  inflating: system/etc/firmware/rtl_nic/rtl8168h-2.fw
  inflating: system/etc/firmware/rtl_nic/rtl8402-1.fw
  inflating: system/etc/firmware/rtl_nic/rtl8411-1.fw
  inflating: system/etc/firmware/rtl_nic/rtl8411-2.fw
Granting required permissions to NetHunter app
   creating: system/etc/firmware/rtlw89/
  inflating: system/etc/firmware/rtlw89/rtw8851b_fw.bin
  inflating: system/etc/firmware/rtlw89/rtw8852a_fw.bin
  inflating: system/etc/firmware/rtlw89/rtw8852b_fw-1.bin
  inflating: system/etc/firmware/rtlw89/rtw8852b_fw.bin
  inflating: system/etc/firmware/rtlw89/rtw8852c_fw.bin
   creating: system/etc/firmware/rtlwifi/
  inflating: system/etc/firmware/rtlwifi/rtl8188efw.bin
  inflating: system/etc/firmware/rtlwifi/rtl8188eufw.bin
  inflating: system/etc/firmware/rtlwifi/rtl8188fufw.bin
  inflating: system/etc/firmware/rtlwifi/rtl8192cfw.bin
  inflating: system/etc/firmware/rtlwifi/rtl8192cfwU.bin
  inflating: system/etc/firmware/rtlwifi/rtl8192cfwU_B.bin
  inflating: system/etc/firmware/rtlwifi/rtl8192cufw.bin
  inflating: system/etc/firmware/rtlwifi/rtl8192cufw_A.bin
  inflating: system/etc/firmware/rtlwifi/rtl8192cufw_B.bin
  inflating: system/etc/firmware/rtlwifi/rtl8192cufw_TMSC.bin
  inflating: system/etc/firmware/rtlwifi/rtl8192defw.bin
  inflating: system/etc/firmware/rtlwifi/rtl8192eefw.bin
  inflating: system/etc/firmware/rtlwifi/rtl8192eu_ap_wowlan.bin
  inflating: system/etc/firmware/rtlwifi/rtl8192eu_nic.bin
  inflating: system/etc/firmware/rtlwifi/rtl8192eu_wowlan.bin
  inflating: system/etc/firmware/rtlwifi/rtl8192fufw.bin
  inflating: system/etc/firmware/rtlwifi/rtl8192sefw.bin
  inflating: system/etc/firmware/rtlwifi/rtl8710bufw_SMIC.bin
  inflating: system/etc/firmware/rtlwifi/rtl8710bufw_UMC.bin
  inflating: system/etc/firmware/rtlwifi/rtl8712u.bin
  inflating: system/etc/firmware/rtlwifi/rtl8723aufw_A.bin
  inflating: system/etc/firmware/rtlwifi/rtl8723aufw_B.bin
  inflating: system/etc/firmware/rtlwifi/rtl8723aufw_B_NoBT.bin
  inflating: system/etc/firmware/rtlwifi/rtl8723befw.bin
  inflating: system/etc/firmware/rtlwifi/rtl8723befw_36.bin
  inflating: system/etc/firmware/rtlwifi/rtl8723bs_ap_wowlan.bin
  inflating: system/etc/firmware/rtlwifi/rtl8723bs_bt.bin
  inflating: system/etc/firmware/rtlwifi/rtl8723bs_nic.bin
  inflating: system/etc/firmware/rtlwifi/rtl8723bs_wowlan.bin
  inflating: system/etc/firmware/rtlwifi/rtl8723bu_ap_wowlan.bin
  inflating: system/etc/firmware/rtlwifi/rtl8723bu_nic.bin
  inflating: system/etc/firmware/rtlwifi/rtl8723bu_wowlan.bin
  inflating: system/etc/firmware/rtlwifi/rtl8723defw.bin
  inflating: system/etc/firmware/rtlwifi/rtl8723fw.bin
  inflating: system/etc/firmware/rtlwifi/rtl8723fw_B.bin
  inflating: system/etc/firmware/rtlwifi/rtl8812aefw.bin
  inflating: system/etc/firmware/rtlwifi/rtl8812aefw_wowlan.bin
  inflating: system/etc/firmware/rtlwifi/rtl8812aufw.bin
  inflating: system/etc/firmware/rtlwifi/rtl8821aefw.bin
  inflating: system/etc/firmware/rtlwifi/rtl8821aefw_29.bin
  inflating: system/etc/firmware/rtlwifi/rtl8821aefw_wowlan.bin
  inflating: system/etc/firmware/rtlwifi/rtl8821aufw.bin
  inflating: system/etc/firmware/rtlwifi/rtl8822befw.bin
   creating: system/etc/firmware/rtw88/
  inflating: system/etc/firmware/rtw88/rtw8723d_fw.bin
  inflating: system/etc/firmware/rtw88/rtw8821c_fw.bin
  inflating: system/etc/firmware/rtw88/rtw8822b_fw.bin
  inflating: system/etc/firmware/rtw88/rtw8822c_fw.bin
  inflating: system/etc/firmware/rtw88/rtw8822c_wow_fw.bin
   creating: system/etc/firmware/zd1211/
  inflating: system/etc/firmware/zd1211/zd1211_ub
  inflating: system/etc/firmware/zd1211/zd1211_uph
  inflating: system/etc/firmware/zd1211/zd1211_uphm
  inflating: system/etc/firmware/zd1211/zd1211_uphr
  inflating: system/etc/firmware/zd1211/zd1211_ur
  inflating: system/etc/firmware/zd1211/zd1211b_ub
  inflating: system/etc/firmware/zd1211/zd1211b_uph
  inflating: system/etc/firmware/zd1211/zd1211b_uphm
  inflating: system/etc/firmware/zd1211/zd1211b_uphr
  inflating: system/etc/firmware/zd1211/zd1211b_ur

Exception occurred while executing 'grant':
java.lang.SecurityException: Permission android.permission.INTERNET requested by com.offsec.nethunter is not a changeable permission type
	at com.android.server.pm.permission.PermissionManagerServiceImpl.grantRuntimePermissionInternal(PermissionManagerServiceImpl.java:1412)
	at com.android.server.pm.permission.PermissionManagerServiceImpl.grantRuntimePermission(PermissionManagerServiceImpl.java:1338)
	at com.android.server.pm.permission.PermissionManagerService.grantRuntimePermission(PermissionManagerService.java:551)
	at android.permission.PermissionManager.grantRuntimePermission(PermissionManager.java:609)
	at com.android.server.pm.PackageManagerShellCommand.runGrantRevokePermission(PackageManagerShellCommand.java:2726)
	at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:305)
	at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
	at android.os.ShellCommand.exec(ShellCommand.java:38)
	at com.android.server.pm.PackageManagerService$IPackageManagerImpl.onShellCommand(PackageManagerService.java:6516)
	at android.os.Binder.shellCommand(Binder.java:1077)
	at android.os.Binder.onTransact(Binder.java:897)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:4473)
	at com.android.server.pm.PackageManagerService$IPackageManagerImpl.onTransact(PackageManagerService.java:6500)
	at android.os.Binder.execTransactInternal(Binder.java:1359)
	at android.os.Binder.execTransact(Binder.java:1284)

Exception occurred while executing 'grant':
java.lang.SecurityException: Permission android.permission.ACCESS_WIFI_STATE requested by com.offsec.nethunter is not a changeable permission type
	at com.android.server.pm.permission.PermissionManagerServiceImpl.grantRuntimePermissionInternal(PermissionManagerServiceImpl.java:1412)
	at com.android.server.pm.permission.PermissionManagerServiceImpl.grantRuntimePermission(PermissionManagerServiceImpl.java:1338)
	at com.android.server.pm.permission.PermissionManagerService.grantRuntimePermission(PermissionManagerService.java:551)
	at android.permission.PermissionManager.grantRuntimePermission(PermissionManager.java:609)
	at com.android.server.pm.PackageManagerShellCommand.runGrantRevokePermission(PackageManagerShellCommand.java:2726)
	at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:305)
	at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
	at android.os.ShellCommand.exec(ShellCommand.java:38)
	at com.android.server.pm.PackageManagerService$IPackageManagerImpl.onShellCommand(PackageManagerService.java:6516)
	at android.os.Binder.shellCommand(Binder.java:1077)
	at android.os.Binder.onTransact(Binder.java:897)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:4473)
	at com.android.server.pm.PackageManagerService$IPackageManagerImpl.onTransact(PackageManagerService.java:6500)
	at android.os.Binder.execTransactInternal(Binder.java:1359)
	at android.os.Binder.execTransact(Binder.java:1284)

Exception occurred while executing 'grant':
java.lang.SecurityException: Permission android.permission.CHANGE_WIFI_STATE requested by com.offsec.nethunter is not a changeable permission type
	at com.android.server.pm.permission.PermissionManagerServiceImpl.grantRuntimePermissionInternal(PermissionManagerServiceImpl.java:1412)
	at com.android.server.pm.permission.PermissionManagerServiceImpl.grantRuntimePermission(PermissionManagerServiceImpl.java:1338)
	at com.android.server.pm.permission.PermissionManagerService.grantRuntimePermission(PermissionManagerService.java:551)
	at android.permission.PermissionManager.grantRuntimePermission(PermissionManager.java:609)
	at com.android.server.pm.PackageManagerShellCommand.runGrantRevokePermission(PackageManagerShellCommand.java:2726)
	at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:305)
	at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
	at android.os.ShellCommand.exec(ShellCommand.java:38)
	at com.android.server.pm.PackageManagerService$IPackageManagerImpl.onShellCommand(PackageManagerService.java:6516)
	at android.os.Binder.shellCommand(Binder.java:1077)
	at android.os.Binder.onTransact(Binder.java:897)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:4473)
	at com.android.server.pm.PackageManagerService$IPackageManagerImpl.onTransact(PackageManagerService.java:6500)
	at android.os.Binder.execTransactInternal(Binder.java:1359)
	at android.os.Binder.execTransact(Binder.java:1284)

Exception occurred while executing 'grant':
java.lang.IllegalArgumentException: Unknown permission: com.offsec.nhterm.permission.RUN_SCRIPT
	at com.android.server.pm.permission.PermissionManagerServiceImpl.grantRuntimePermissionInternal(PermissionManagerServiceImpl.java:1381)
	at com.android.server.pm.permission.PermissionManagerServiceImpl.grantRuntimePermission(PermissionManagerServiceImpl.java:1338)
	at com.android.server.pm.permission.PermissionManagerService.grantRuntimePermission(PermissionManagerService.java:551)
	at android.permission.PermissionManager.grantRuntimePermission(PermissionManager.java:609)
	at com.android.server.pm.PackageManagerShellCommand.runGrantRevokePermission(PackageManagerShellCommand.java:2726)
	at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:305)
	at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
	at android.os.ShellCommand.exec(ShellCommand.java:38)
	at com.android.server.pm.PackageManagerService$IPackageManagerImpl.onShellCommand(PackageManagerService.java:6516)
	at android.os.Binder.shellCommand(Binder.java:1077)
	at android.os.Binder.onTransact(Binder.java:897)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:4473)
	at com.android.server.pm.PackageManagerService$IPackageManagerImpl.onTransact(PackageManagerService.java:6500)
	at android.os.Binder.execTransactInternal(Binder.java:1359)
	at android.os.Binder.execTransact(Binder.java:1284)

Exception occurred while executing 'grant':
java.lang.IllegalArgumentException:
</details>

**Comment by Xkirnel99** [comment]
Me too
